### ISSUE TITLE
Failed to add cloud-archive repository to ROCK

### ISSUE THREAD

**Issue by gboutry** [canonical/rockcraft#220]
I've tried adding the cloud archive's repository to my rock without much success:

```yaml
package-repositories:
  - type: apt
    ppa: cloud-archive:antelope
    priority: always
```

Error:
```
2023-03-28 14:26:00.951 :: 2023-03-28 12:26:00.306 Installing package repositories
2023-03-28 14:26:00.951 :: 2023-03-28 12:26:00.306 Failed to install PPA 'cloud-archive:antelope': invalid PPA format
2023-03-28 14:26:00.951 :: 2023-03-28 12:26:00.310 Traceback (most recent call last):
2023-03-28 14:26:00.951 :: 2023-03-28 12:26:00.311   File "/snap/rockcraft/663/lib/python3.8/site-packages/rockcraft/parts.py", line 130, in run
2023-03-28 14:26:00.951 :: 2023-03-28 12:26:00.311     self._install_package_repositories()
2023-03-28 14:26:00.951 :: 2023-03-28 12:26:00.311   File "/snap/rockcraft/663/lib/python3.8/site-packages/rockcraft/parts.py", line 164, in _install_package_repositories
2023-03-28 14:26:00.951 :: 2023-03-28 12:26:00.311     refresh_required = repo.install(
2023-03-28 14:26:00.951 :: 2023-03-28 12:26:00.311   File "/snap/rockcraft/663/lib/python3.8/site-packages/craft_archives/repo/installer.py", line 51, in install
2023-03-28 14:26:00.951 :: 2023-03-28 12:26:00.311     refresh_required |= key_manager.install_package_repository_key(
2023-03-28 14:26:00.951 :: 2023-03-28 12:26:00.311   File "/snap/rockcraft/663/lib/python3.8/site-packages/craft_archives/repo/apt_key_manager.py", line 238, in install_package_repository_key
2023-03-28 14:26:00.951 :: 2023-03-28 12:26:00.311     key_id = apt_ppa.get_launchpad_ppa_key_id(ppa=package_repo.ppa)
2023-03-28 14:26:00.951 :: 2023-03-28 12:26:00.311   File "/snap/rockcraft/663/lib/python3.8/site-packages/craft_archives/repo/apt_ppa.py", line 43, in get_launchpad_ppa_key_id
2023-03-28 14:26:00.951 :: 2023-03-28 12:26:00.311     owner, name = split_ppa_parts(ppa=ppa)
2023-03-28 14:26:00.951 :: 2023-03-28 12:26:00.311   File "/snap/rockcraft/663/lib/python3.8/site-packages/craft_archives/repo/apt_ppa.py", line 36, in split_ppa_parts
2023-03-28 14:26:00.951 :: 2023-03-28 12:26:00.311     raise errors.AptPPAInstallError(ppa, "invalid PPA format")
2023-03-28 14:26:00.951 :: 2023-03-28 12:26:00.311 craft_archives.repo.errors.AptPPAInstallError: Failed to install PPA 'cloud-archive:antelope': invalid PPA format
```

Snap info:
```bash 
$ snap info rockcraft
name:      rockcraft
summary:   A craft like experience to create ROCKS
publisher: Sergio Schvezov ⭐ (sergiusens)
store-url: https://snapcraft.io/rockcraft
license:   GPL-3.0
description: |
  Rockcraft aims to take the same primitives used in Charmcraft and Snapcraft
  to create OCI images.
commands:
  - rockcraft
snap-id:      3mPIBn6L9IYLyBAZsaqjlnMk7huEtqlv
tracking:     latest/edge
refresh-date: 2 days ago, at 12:35 CEST
channels:
  latest/stable:    –                                   
  latest/candidate: –                                   
  latest/beta:      –                                   
  latest/edge:      0+git.2b41660 2023-03-24 (663) 84MB classic
installed:          0+git.2b41660            (663) 84MB classic
```

The command I usually use to add the repository is: `add-apt-repository cloud-archive:antelope`
I think the issue might be that it's not a PPA ?

**Comment by gboutry** [comment]
Looks like for now, the working way to add the repo is:
```yaml
package-repositories:
  - type: apt
    formats: [deb, deb-src]
    components: [main]
    suites: [jammy-updates/antelope]
    key-id: 391A9AA2147192839E9DB0315EDB1B62EC4926EA
    url: http://ubuntu-cloud.archive.canonical.com/ubuntu
    priority: always
```

**Comment by tigarmo** [comment]
The [syntax](https://snapcraft.io/docs/package-repositories#heading--ppa) for ppas is `<ppa-owner>/<ppa-name>`, so in this case it's probably a matter of figuring out the correct owner and name.

**Comment by tigarmo** [comment]
Ah that's interesting; I think it might make sense to add a new `cloud` repo type sure. Thanks for the suggestion!

**Comment by gboutry** [comment]
Yeah, something like the following would be great!

```yaml
package-repositories:
  - type: apt
    cloud-archive: antelope # or cloud:
    priority: always
```
